name: Kevin och Mikael
on: [push]
jobs: 
  build: 
    name: Build this
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
    with: 
      dotnet-version: 5.0.x
    -name: Bygg det här
    run: dotnet build